config/routes.rb
Rails.application.routes.draw do
  get 'static/home'

  get 'static/about'

  get 'static/contact'

  resources :notaries

  resources :clients

  devise_for :users
  get 'home/index'

  get 'home/show'

  devise_for :admins
  resources :organizations

  get 'profiles/show'
  get 'profiles/index'

  match '/' => 'profiles#show', :constraints => { :subdomain => /.+/ } ,via: [:get, :post]

  resources :blogs
  root 'home#index'

end

app/models/notary.rb
class Notary < ActiveRecord::Base
	belongs_to :client
end

app/controllers/notaries_controller.rb
class NotariesController < ApplicationController
  before_action :set_notary, only: [:show, :edit, :update, :destroy]

  # GET /notaries
  # GET /notaries.json
  def index
    @notaries = Notary.all
  end

  # GET /notaries/1
  # GET /notaries/1.json
  def show
  end

  # GET /notaries/new
  def new
    @notary = Notary.new
  end

  # GET /notaries/1/edit
  def edit
  end

  # POST /notaries
  # POST /notaries.json
  def create
    @notary = Notary.new(notary_params)

    respond_to do |format|
      if @notary.save
        format.html { redirect_to @notary, notice: 'Notary was successfully created.' }
        format.json { render :show, status: :created, location: @notary }
      else
        format.html { render :new }
        format.json { render json: @notary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notaries/1
  # PATCH/PUT /notaries/1.json
  def update
    respond_to do |format|
      if @notary.update(notary_params)
        format.html { redirect_to @notary, notice: 'Notary was successfully updated.' }
        format.json { render :show, status: :ok, location: @notary }
      else
        format.html { render :edit }
        format.json { render json: @notary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notaries/1
  # DELETE /notaries/1.json
  def destroy
    @notary.destroy
    respond_to do |format|
      format.html { redirect_to notaries_url, notice: 'Notary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notary
      @notary = Notary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notary_params
      params.require(:notary).permit(:name, :info)
    end
end

app/helpers/notaries_helper.rb
module NotariesHelper
end

app/views/notaries/_form.html.erb
<%= simple_form_for(@notary) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :info %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notaries/edit.html.erb
<h1>Editing notary</h1>

<%= render 'form' %>

<%= link_to 'Show', @notary %> |
<%= link_to 'Back', notaries_path %>

app/views/notaries/index.html.erb
<h1>Listing notaries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notaries.each do |notary| %>
      <tr>
        <td><%= notary.name %></td>
        <td><%= notary.info %></td>
        <td><%= link_to 'Show', notary %></td>
        <td><%= link_to 'Edit', edit_notary_path(notary) %></td>
        <td><%= link_to 'Destroy', notary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notary', new_notary_path %>

app/views/notaries/new.html.erb
<h1>New notary</h1>

<%= render 'form' %>

<%= link_to 'Back', notaries_path %>

app/views/notaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notary.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @notary.info %>
</p>

<%= link_to 'Edit', edit_notary_path(@notary) %> |
<%= link_to 'Back', notaries_path %>